name: ecopulse
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  crypto: ^3.0.3
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_tts: ^4.2.2
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.5
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.16
  path_provider_foundation: ^2.4.1
  path_provider_platform_interface: ^2.1.2
  provider: ^6.1.4
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.8
  shared_preferences_foundation: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.3
  sign_in_with_apple: ^6.1.4
  sqflite: ^2.4.2
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.15
  url_launcher_ios: ^6.3.3
  url_launcher_platform_interface: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
